# Generated by Django 5.1.2 on 2024-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diytours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
